version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: memorina_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Memorina@150203
      MYSQL_DATABASE: memorina
      MYSQL_USER: memorina_user
      MYSQL_PASSWORD: Memorina@150203
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
    networks:
      - shared-network


networks:
  shared-network:
    external: true
    
volumes:
  mysql_data:

  
